---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 1
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
  image:
    application: nivavin/cp-server-connect-with-datagen:$TAG
    init: confluentinc/confluent-init-container:$INIT_TAG
  tls:
    secretRef: tls-connect 
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      tls:
        enabled: true

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    platform.confluent.io/cr-name: connect
    platform.confluent.io/namespace: confluent
    platform.confluent.io/type: connect
    prometheus.io/port: "7778"
    prometheus.io/scrape: "true"
  name: connect-bootstrap
  namespace: confluent
  labels:
    confluent-platform: "true"
    cr-name: connect
    type: connect
spec:
  ports:
    - name: external
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: connect
    clusterId: confluent
    confluent-platform: "true"
    type: connect
  sessionAffinity: None
  type: ClusterIP
