---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
  image:
    application: confluentinc/cp-server:$TAG
    init: confluentinc/confluent-init-container:$INIT_TAG
  dataVolumeCapacity: 10Gi
  tls:
    secretRef: tls-kafka
  listeners:
    internal:
      tls:
        enabled: true
    external:
      tls: 
        enabled: true
      #externalAccess:
      #  type: loadBalancer
        #loadBalancer:
        #  domain: mycfk.com
        #  brokerPrefix: rb
        #  bootstrapPrefix: rb
        #  annotations:
        #    service.beta.kubernetes.io/aws-load-balancer-type: nlb
        #    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  metricReporter:
    enabled: true
    bootstrapEndpoint: kafka:9071
    tls:
      enabled: true
  configOverrides:
    server:
      - confluent.balancer.heal.uneven.load.trigger=ANY_UNEVEN_LOAD
      - auto.create.topics.enable=true
    log4j:
      - log4j.logger.kafka.authorizer.logger=DEBUG, stdout
  dependencies:
    zookeeper:
      endpoint: zookeeper.confluent.svc.cluster.local:2182
      tls:
        enabled: true
