apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: connect
  namespace: confluent
spec:
  principal:
    type: user
    name: connect
  role: ResourceOwner
  clustersScopeByIds:
    connectClusterId: confluent.connect
  resourcePatterns:
    - name: datagen-users
      patternType: LITERAL
      resourceType: Connectors
  resourcePatterns:
    - name: datagen-pageviews
      patternType: LITERAL
      resourceType: Connectors
