---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  podTemplate:
    probe:
      liveness:
        periodSeconds: 10
        failureThreshold: 5
        timeoutSeconds: 500
  image:
    application: confluentinc/cp-enterprise-control-center:$TAG
    init: confluentinc/confluent-init-container:$INIT_TAG
  dataVolumeCapacity: 10Gi
  authorization:
    type: rbac
#  externalAccess:
#    type: loadBalancer
#    loadBalancer:
#      domain: my.domain
#      prefix: rb-c3
  tls:
    secretRef: tls-controlcenter
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.confluent.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: c3-mds-client
      tls:
        enabled: true
    connect:
      - name: connect
        url:  https://connect.confluent.svc.cluster.local:8083
        tls:
          enabled: true
    ksqldb:
      - name: ksqldb
        url:  https://ksqldb.confluent.svc.cluster.local:8088
        tls:
          enabled: true
    schemaRegistry:
      url: https://schemaregistry.confluent.svc.cluster.local:8081
      tls:
        enabled: true

---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: c3-kafka-user1
  namespace: confluent
spec:
  principal:
    type: user
    name: user1
  role: ClusterAdmin

---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: c3-sr-user1
  namespace: confluent
spec:
  principal:
    type: user
    name: user1
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_confluent
  role: SystemAdmin

---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: c3-connect-user1
  namespace: confluent
spec:
  principal:
    type: user
    name: user1
  clustersScopeByIds:
    connectClusterId: confluent.connect
  role: SystemAdmin

---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: c3-ksqldb-user1
  namespace: confluent
spec:
  principal:
    type: user
    name: user1
  clustersScopeByIds:
    ksqlClusterId: confluent.ksqldb_
  role: ClusterAdmin

---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: c3-ksqldb-group-user1
  namespace: confluent
spec:
  principal:
    type: user
    name: user1
  role: ResourceOwner
  resourcePatterns:
    - name: _confluent-ksql-confluent.ksqldb_
      patternType: PREFIXED
      resourceType: Group

