---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: test
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 3
  configs:
    cleanup.policy: "delete"
  kafkaClusterRef:
    name: kafka
    namespace: confluent
  kafkaRest:
    authentication:
      type: bearer
      bearer:
        secretRef: rest-credential
  
