broker.id=1
advertised.listeners=INTERNAL://kafka2:29091,TOKEN://kafka2:20091,SSL://kafka2:21091,CLEAR://localhost:9093
listener.security.protocol.map=INTERNAL:SASL_PLAINTEXT,TOKEN:SASL_SSL,SSL:SSL,CLEAR:PLAINTEXT
listeners=INTERNAL://0.0.0.0:29091,TOKEN://0.0.0.0:20091,SSL://0.0.0.0:21091,CLEAR://0.0.0.0:9093
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
log.dirs=/var/lib/kafka/data
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
confluent.license.topic.replication.factor=1
offsets.topic.replication.factor=1
confluent.security.event.logger.exporter.kafka.topic.replicas=1
default.replication.factor=1
confluent.license.topic.replication.factor=1
confluent.balancer.topic.replication.factor=1
confluent.license=
log.retention.hours=168
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000
zookeeper.connect=zookeeper:2181
zookeeper.connection.timeout.ms=6000
confluent.support.metrics.enable=true
confluent.support.customer.id=anonymous
inter.broker.listener.name=SSL
#sasl.mechanism.inter.broker.protocol=PLAIN
super.users=User:admin;User:mds;User:superUser;User:ANONYMOUS;User:kafka1;User:kafka2
listener.name.internal.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
              username="admin" \
              password="admin-secret" \
              user_admin="admin-secret" \
              user_mds="mds-secret";
sasl.enabled.mechanisms=PLAIN, OAUTHBEARER

listener.name.ssl.ssl.principal.mapping.rules=RULE:^CN=([a-zA-Z0-9.]*).*$/$1/L, DEFAULT

listener.name.token.sasl.enabled.mechanisms=OAUTHBEARER
listener.name.token.oauthbearer.sasl.server.callback.handler.class=io.confluent.kafka.server.plugins.auth.token.TokenBearerValidatorCallbackHandler
listener.name.token.oauthbearer.sasl.login.callback.handler.class=io.confluent.kafka.server.plugins.auth.token.TokenBearerServerLoginCallbackHandler
listener.name.token.oauthbearer.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required publicKeyPath="/etc/kafka/secrets/mds/public.pem";
listener.name.token.ssl.keystore.password=confluent
listener.name.token.ssl.keystore.location=/etc/kafka/secrets/kafka2.keystore.jks
listener.name.token.ssl.client.auth=required
listener.name.token.ssl.truststore.location=/etc/kafka/secrets/kafka2.truststore.jks
listener.name.token.ssl.truststore.password=confluent
listener.name.token.ssl.key.credentials=confluent


#metrics reporter
metric.reporters=io.confluent.metrics.reporter.ConfluentMetricsReporter
confluent.metrics.reporter.bootstrap.servers=kafka2:29091
confluent.metrics.reporter.topic.replicas=1
confluent.metrics.reporter.security.protocol=SASL_PLAINTEXT
confluent.metrics.reporter.sasl.mechanism=PLAIN
confluent.metrics.reporter.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
confluent.metrics.reporter.max.request.size=10485760

ssl.keystore.password=confluent
ssl.keystore.location=/etc/kafka/secrets/kafka2.keystore.jks
ssl.truststore.location=/etc/kafka/secrets/kafka2.truststore.jks
ssl.truststore.password=confluent
ssl.key.credentials=confluent
ssl.client.auth=required

zookeeper.set.acl=true


confluent.schema.registry.url: https://schemaregistry:8081
confluent.schema.registry.basic.auth.credentials.source=USER_INFO
confluent.schema.registry.basic.auth.info=superUser:superUser
confluent.basic.auth.credentials.source=USER_INFO
confluent.basic.auth.user.info=superUser:superUser



confluent.metadata.server.advertised.listeners=http://kafka2:28090,https://kafka2:28091
confluent.metadata.server.listeners=http://0.0.0.0:28090,https://0.0.0.0:28091
confluent.metadata.server.token.auth.enable=true
confluent.metadata.server.authentication.method=BEARER
confluent.metadata.topic.replication.factor=1
confluent.metadata.server.token.max.lifetime.ms=3600000
confluent.metadata.server.token.signature.algorithm=RS256
confluent.metadata.server.public.key.path=/etc/kafka/secrets/mds/public.pem
confluent.metadata.server.token.key.path=/etc/kafka/secrets/mds/keypair.pem
confluent.metadata.server.ssl.truststore.location=/etc/kafka/secrets/kafka2.truststore.jks
confluent.metadata.server.ssl.truststore.password=confluent
confluent.metadata.server.ssl.keystore.location=/etc/kafka/secrets/kafka2.keystore.jks
confluent.metadata.server.ssl.keystore.password=confluent
confluent.metadata.server.ssl.key.password=confluent

authorizer.class.name=io.confluent.kafka.security.authorizer.ConfluentServerAuthorizer
confluent.authorizer.access.rule.providers=CONFLUENT,ZK_ACL
confluent.authorizer.group.provider=RBAC

ldap.com.sun.jndi.ldap.read.timeout=3000
ldap.java.naming.provider.url=ldap://openldap:389
ldap.java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory
ldap.java.naming.security.authentication=simple


#ldap.java.naming.security.principal=cn=ldapAdmin,ou=users,dc=example,dc=com
#ldap.java.naming.security.credentials=ldapAdmin
#ldap.group.search.base=ou=groups,dc=example,dc=com
#ldap.search.mode=GROUPS
#ldap.group.name.attribute=cn
#ldap.group.member.attribute.pattern=cn=(.*),ou=users,dc=example,dc=com
#ldap.user.search.base=ou=user,dc=example,dc=com
#ldap.user.name.attribute=uid
#ldap.user.object.class=inetOrgPerson
#ldap.user.search.scope=2

ldap.java.naming.security.principal=cn=admin,dc=example,dc=com
ldap.java.naming.security.credentials=admin
ldap.group.member.attribute=memberuid
ldap.group.object.class=posixGroup
ldap.user.object.class=inetOrgPerson
ldap.search.mode=GROUPS
ldap.group.search.base=ou=groups,dc=example,dc=com
ldap.user.name.attribute=uid
ldap.user.search.base=ou=users,dc=example,dc=com
ldap.group.name.attribute=cn
ldap.group.member.attribute.pattern=cn=(.*),ou=users,dc=example,dc=com

#Below setup: binding DN is in Manager group, all other users in Developers group
#ldap.group.search.filter=(|(cn=Manager,dc=example,dc=com)(dc=example,dc=com))
#ldap.group.member.attribute.pattern=uid=(\\w+),(ou=Developers,dc=example,dc=com|dc=example,dc=com)


#For USERS search mode
#ldap.search.mode=USERS
#ldap.user.object.class=inetOrgPerson
#ldap.user.search.base=ou=users,dc=example,dc=com
#ldap.group.name.attribute=cn
#ldap.group.object.class=posixGroup
#ldap.group.member.attribute.pattern=cn=(.*),ou=users,dc=example,dc=com
#ldap.group.search.base=ou=groups,dc=example,dc=com
#ldap.user.search.scope=2
#ldap.user.memberof.attribute=memberOf
#ldap.user.memberof.attribute.pattern=cn=(.*),ou=groups,dc=example,dc=com
#ldap.user.search.filter=(memberOf=CN=Kafka,ou=groups,DC=example,DC=com)
#ldap.user.name.attribute=uid
