---
version: '3.4'
services:
  zookeeper3:
    environment:
      ZOOKEEPER_SERVERS: zookeeper1:12888:13888;zookeeper2:22888:23888;zookeeper3:32888:33888
      ZOOKEEPER_GROUPS: 
      ZOOKEEPER_WEIGHTS:

  zookeeper1:
    environment:
      ZOOKEEPER_SERVERS: zookeeper1:12888:13888;zookeeper2:22888:23888;zookeeper3:32888:33888
      ZOOKEEPER_GROUPS: 
      ZOOKEEPER_WEIGHTS:

  zookeeper2:
    environment:
      ZOOKEEPER_SERVERS: zookeeper1:12888:13888;zookeeper2:22888:23888;zookeeper3:32888:33888
      ZOOKEEPER_GROUPS: 
      ZOOKEEPER_WEIGHTS:
