sasl.mechanism=PLAIN
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="mds" password="mds";
ssl.truststore.location=./secrets/client.truststore.jks
ssl.truststore.password=confluent
