bootstrap.servers=kafka1:10091,kafka2:20091
host.name=ksql-server
ksql.service.id=ksql-cluster
ksql.streams.replicator.factor=1
ksql.internal.topic.replicas=1
ksql.sink.replicas=1
ksql.streams.num.stream.threads=1

ksql.logging.processing.topic.replication.factor=1
ksql.logging.processing.topic.auto.create=true
ksql.logging.processing.stream.auto.create=true

listeners=https://0.0.0.0:8088
cache.max.bytes.buffering=0

ksql.security.extension.class=io.confluent.ksql.security.KsqlConfluentSecurityExtension

rest.servlet.initializor.classes=io.confluent.common.security.jetty.initializer.InstallBearerOrBasicSecurityHandler
websocket.servlet.initializor.classes=io.confluent.common.security.jetty.initializer.InstallBearerOrBasicSecurityHandler
oauth.jwt.public.key.path=/etc/kafka/secrets/mds/public.pem
confluent.metadata.public.key.path=/etc/kafka/secrets/mds/public.pem
public.key.path=/etc/kafka/secrets/mds/public.pem

confluent.metadata.bootstrap.server.urls=http://kafka1:18090,http://kafka2:28090
confluent.metadata.http.auth.credentials.provider=BASIC
confluent.metadata.basic.auth.credentials.provider=USER_INFO
confluent.metadata.basic.auth.user.info=ksqlAdmin:ksqlAdmin

ssl.keystore.password=confluent
ssl.keystore.location=/etc/kafka/secrets/ksqldb-server.keystore.jks
ssl.truststore.location=/etc/kafka/secrets/ksqldb-server.truststore.jks
ssl.truststore.password=confluent
ssl.key.password=confluent
ssl.endpoint.identification.algorithm=https

ksql.schema.registry.url=https://schemaregistry:8081
ksql.schema.registry.ssl.truststore.location=/etc/kafka/secrets/ksqldb-server.truststore.jks
ksql.schema.registry.ssl.keystore.location=/etc/kafka/secrets/ksqldb-server.keystore.jks
ksql.schema.registry.ssl.trustore.password=confluent
ksql.schema.registry.ssl.keystore.password=confluent
ksql.schema.registry.ssl.key.password=confluent
ksql.schema.registry.basic.auth.credentials.source=USER_INFO
ksql.schema.registry.basic.auth.user.info=ksqlAdmin:ksqlAdmin

security.protocol=SASL_SSL
sasl.mechanism=OAUTHBEARER
sasl.login.callback.handler.class=io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler
sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required username="ksqlAdmin" password="ksqlAdmin" metadataServerUrls="http://kafka1:18090,http://kafka2:28090";


producer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
consumer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
confluent.monitoring.interceptor.security.protocol=SASL_SSL
confluent.monitoring.interceptor.ssl.keystore.password=confluent
confluent.monitoring.interceptor.ssl.keystore.location=/etc/kafka/secrets/ksqldb-server.keystore.jks
confluent.monitoring.interceptor.ssl.truststore.location=/etc/kafka/secrets/ksqldb-server.truststore.jks
confluent.monitoring.interceptor.ssl.truststore.password=confluent
confluent.monitoring.interceptor.ssl.key.password=confluent
confluent.monitoring.interceptor.sasl.mechanism=OAUTHBEARER
confluent.monitoring.interceptor.sasl.login.callback.handler.class=io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler
confluent.monitoring.interceptor.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required username="ksqlAdmin" password="ksqlAdmin" metadataServerUrls="http://kafka1:18090,http://kafka2:28090";




