---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 1
  image:
    application: nivavin/cp-server-connect-with-datagen:$TAG
    init: confluentinc/confluent-init-container:$INIT_TAG
  tls:
    directoryPathInContainer: /vault/secrets
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-init-first: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/role: "connect"
      vault.hashicorp.com/log-level: "trace"
      vault.hashicorp.com/agent-inject-secret-database-config.txt: "internal/data/database/postgres"
      vault.hashicorp.com/agent-inject-template-database-config.txt: |
        {{- with secret "internal/data/database/postgres" -}}
           password={{ .Data.data.password }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-jksPassword.txt: "internal/data/keystore/jksPassword.txt"
      vault.hashicorp.com/agent-inject-template-jksPassword.txt: |
        {{- with secret "internal/data/keystore/jksPassword.txt" -}}
        {{ .Data.data.password }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-keystore.jks: "internal/data/keystore/connect.keystore.jks"
      vault.hashicorp.com/agent-inject-template-keystore.jks: |
        {{- with secret "internal/data/keystore/connect.keystore.jks" -}}
        {{ .Data.data.keystore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-truststore.jks: "internal/data/keystore/connect.truststore.jks"
      vault.hashicorp.com/agent-inject-template-truststore.jks: |
        {{- with secret "internal/data/keystore/connect.truststore.jks" -}}
        {{ .Data.data.keystore | base64Decode }}
        {{- end }}
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      tls:
        enabled: true
    schemaRegistry:
      url: https://schemaregistry.confluent.svc.cluster.local:8081
      tls:
        enabled: true


---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-schema-registry:$TAG
    init: confluentinc/confluent-init-container:$INIT_TAG
  tls:
    directoryPathInContainer: /vault/secrets
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-init-first: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/role: "connect"
      vault.hashicorp.com/agent-inject-secret-jksPassword.txt: "internal/data/keystore/jksPassword.txt"
      vault.hashicorp.com/agent-inject-template-jksPassword.txt: |
        {{- with secret "internal/data/keystore/jksPassword.txt" -}}
        {{ .Data.data.password }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-keystore.jks: "internal/data/keystore/schemaregistry.keystore.jks"
      vault.hashicorp.com/agent-inject-template-keystore.jks: |
        {{- with secret "internal/data/keystore/schemaregistry.keystore.jks" -}}
        {{ .Data.data.keystore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-truststore.jks: "internal/data/keystore/schemaregistry.truststore.jks"
      vault.hashicorp.com/agent-inject-template-truststore.jks: |
        {{- with secret "internal/data/keystore/schemaregistry.truststore.jks" -}}
        {{ .Data.data.keystore | base64Decode }}
        {{- end }}
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      tls:
        enabled: true


