version: '3.4'
services:
  kafka1:
    depends_on:
      - zookeeper1
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:12181"

  connect:
    ports:
      - "8083:8083"
    volumes:
      - ./jar:/usr/share/java/jar
    environment:
      CLASSPATH: '/usr/share/java/jar/confluentinc-kafka-connect-replicator/lib/replicator-rest-extension-$TAG.jar'
      CONNECT_BOOTSTRAP_SERVERS: "kafka1:19093"
      CONNECT_REST_EXTENSION_CLASSES: io.confluent.connect.replicator.monitoring.ReplicatorMonitoringExtension
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor

  controlcenter:
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka1:19093"
    
