---
- hosts: openldap.example.com
  remote_user: centos
  become: true
  tasks:
  - include_role:
      name: ldap
    vars:
      ssl: true
      ssl_ca_cert: '../certs/ca.crt'
      ssl_cert: '../certs/openldap.example.com-ca-signed.crt'
      ssl_private_key: '../certs/openldap.example.com.key'

