security.protocol=SASL_SSL
sasl.mechanism=PLAIN
ssl.truststore.location=./secrets/client.truststore.jks
ssl.truststore.password=confluent
# SSL  Setup
#ssl.truststore.location=/var/ssl/private/broker.truststore.jks
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
     username="kafka" \
     password="kafka-secret";
