SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
CREATE TABLE student (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

INSERT INTO student(name) VALUES 
('Alex'),
('John'),
('Alford'),
('Ravi'),
('Benjamin');
