---

- name: Provision EC2 security group
  ec2_group:
    name: "{{ item.name }}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
    description: "{{ item.description }}"
    region: "{{ item.region }}"
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
    rules: "{{ item.rules }}"
    rules_egress: "{{ item.rules_egress }}"
  with_items: "{{ aws_security_groups }}"
  register: ec2_group


- name: Provision instance
  ec2:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
    key_name: "{{ item.sshkey_name }}"
    instance_type: "{{ item.instance_type }}"
    image: "{{ aws_ami }}"
    wait: yes
    group: "{{ item.security_group}}"
    wait_timeout: 500
    exact_count: "{{ item.exact_count }}"
    count_tag:
      Name: "{{ item.tag_name }}"
      Environment: "{{ item.tag_environment }}"
    instance_tags:
      Name: "{{ item.tag_name }}"
      Environment: "{{ item.tag_environment }}"
    region: "{{ item.region }}"
    assign_public_ip: yes
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    volumes:
    - device_name: /dev/sda1
      volume_type: gp2
      volume_size: "{{ item.volume_size }}"
      delete_on_termination: "{{ item.delete_vol_on_termination }}"
  with_items: "{{ aws_ec2_instances }}"
