listeners=https://0.0.0.0:8081
kafkastore.connection.url=zookeeper:2181
kafkastore.bootstrap.servers=SASL_SSL://kafka1:10091,SASL_SSL://kafka2:20091
schema.registry.group.id=schema-registry
host.name=schemaregistry
kafkastore.topic=_schemas
kafkastore.topic.replication.factor=2
kafkastore.security.protocol=SASL_SSL
kafkastore.sasl.mechanism=OAUTHBEARER
kafkastore.sasl.login.callback.handler.class=io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler
kafkastore.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
              username="schemaregistryUser" \
              password="schemaregistryUser" \
              metadataServerUrls="http://kafka1:18090,http://kafka2:28090";
kafkastore.ssl.key.password=confluent
kafkastore.ssl.truststore.password=confluent
kafkastore.ssl.truststore.location=/etc/kafka/secrets/schemaregistry.truststore.jks
kafkastore.ssl.keystore.location=/etc/kafka/secrets/schemaregistry.keystore.jks
kafkastore.ssl.keystore.password=confluent
kafkastore.ssl.endpoint.identification.algorithm=https
ssl.key.password=confluent
ssl.truststore.password=confluent
ssl.truststore.location=/etc/kafka/secrets/schemaregistry.truststore.jks
ssl.keystore.location=/etc/kafka/secrets/schemaregistry.keystore.jks
ssl.keystore.password=confluent
schema.registry.inter.instance.protocol=https
ssl.cipher.suites=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
debug=false

schema.registry.resource.extension.class=io.confluent.kafka.schemaregistry.security.SchemaRegistrySecurityResourceExtension
confluent.schema.registry.authorizer.class=io.confluent.kafka.schemaregistry.security.authorizer.rbac.RbacAuthorizer
rest.servlet.initializor.classes=io.confluent.common.security.jetty.initializer.InstallBearerOrBasicSecurityHandler
public.key.path=/etc/kafka/secrets/mds/public.pem
confluent.schema.registry.auth.mechanism=JETTY_AUTH

confluent.metadata.bootstrap.server.urls=http://kafka1:18090,http://kafka2:28090
confluent.metadata.http.auth.credentials.provider=BASIC
confluent.metadata.basic.auth.user.info=schemaregistryUser:schemaregistryUser

# This enables anonymous access with a principal of User:ANONYMOUS
confluent.schema.registry.anonymous.principal=true
authentication.skip.paths=/*

confluent.license=
confluent.license.topic.replication.factor=1
confluent.topic.replication.factor=1
