zookeeper.connect=zookeeper:2181
bootstrap.servers=kafka1:10091,kafka2:20091
confluent.controlcenter.internal.topics.partitions=2
confluent.controlcenter.internal.topics.replication=1
confluent.controlcenter.command.topic.replication=1
confluent.metrics.topic.replication=1
confluent.controlcenter.replication.factor=1
confluent.monitoring.interceptor.topic.replication=1
confluent.monitoring.interceptor.topic.partitions=1
replication.factor=1
confluent.controlcenter.id=0
confluent.controlcenter.data.dir=/var/lib/confluent/control-center
confluent.controlcenter.log.dir=/var/log/confluent/control-center

confluent.controlcenter.streams.cache.max.bytes.buffering=100000000
confluent.controlcenter.streams.consumer.request.timeout.ms=960032
confluent.controlcenter.streams.num.stream.threads=1


confluent.controlcenter.streams.ssl.keystore.password=confluent
confluent.controlcenter.streams.ssl.keystore.location=/etc/kafka/secrets/controlcenter.keystore.jks
confluent.controlcenter.streams.ssl.truststore.location=/etc/kafka/secrets/controlcenter.truststore.jks
confluent.controlcenter.streams.ssl.truststore.password=confluent
confluent.controlcenter.streams.ssl.key.password=confluent
confluent.controlcenter.streams.ssl.endpoint.identification.algorithm=https

confluent.controlcenter.streams.security.protocol=SASL_SSL
confluent.controlcenter.streams.sasl.mechanism=OAUTHBEARER
confluent.controlcenter.streams.sasl.login.callback.handler.class=io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler
confluent.controlcenter.streams.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required username="c3Admin" password="c3Admin" metadataServerUrls="http://kafka1:18090,http://kafka2:28090";

confluent.controlcenter.rest.listeners=http://0.0.0.0:9021,https://0.0.0.0:9022
confluent.controlcenter.rest.ssl.keystore.password=confluent
confluent.controlcenter.rest.ssl.keystore.location=/etc/kafka/secrets/controlcenter.keystore.jks
confluent.controlcenter.rest.ssl.truststore.location=/etc/kafka/secrets/controlcenter.truststore.jks
confluent.controlcenter.rest.ssl.truststore.password=confluent
confluent.controlcenter.rest.ssl.key.password=confluent

confluent.controlcenter.connect.Connect.cluster=https://connect:8083

confluent.controlcenter.ksql.KSQL.url=https://ksqldb-server:8088
confluent.controlcenter.ksql.KSQL.advertised.url=https://ksqldb-server:8088

confluent.controlcenter.schema.registry.url=https://schemaregistry:8081
confluent.controlcenter.schema.registry.ssl.truststore.location=/etc/kafka/secrets/controlcenter.truststore.jks
confluent.controlcenter.schema.registry.ssl.truststore.password=confluent

confluent.controlcenter.rest.authentication.method=BEARER
public.key.path=/etc/kafka/secrets/mds/public.pem

confluent.metadata.bootstrap.server.urls=http://kafka1:18090,http://kafka2:28090
confluent.metadata.basic.auth.user.info=c3Admin:c3Admin




