bootstrap.servers=SASL_SSL://kafka1:10091,SASL_SSL://kafka2:20091
rest.port=8083
rest.advertised.host.name=connect
listeners=https://0.0.0.0:8083
group.id=connect-cluster
producer.client.id=connect-worker-producer
offset.flush.interval.ms=10000

offset.storage.topic=connect-offsets
config.storage.topic=connect-configs
status.storage.topic=connect-status
offset.storage.replication.factor=1
config.storage.replication.factor=1
status.storage.replication.factor=1
replication.factor=1

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=io.confluent.connect.avro.AvroConverter
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schema.registry.url=http://schemaregistry:8081
producer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
consumer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor

ssl.endpoint.identification.algorithm=https
security.protocol=SASL_SSL
ssl.keystore.password=confluent
ssl.keystore.location=/etc/kafka/secrets/connect.keystore.jks
ssl.truststore.location=/etc/kafka/secrets/connect.truststore.jks
ssl.truststore.password=confluent
ssl.key.password=confluent

producer.security.protocol=SASL_SSL
producer.ssl.keystore.password=confluent
producer.ssl.keystore.location=/etc/kafka/secrets/connect.keystore.jks
producer.ssl.truststore.location=/etc/kafka/secrets/connect.truststore.jks
producer.ssl.truststore.password=confluent
producer.ssl.key.password=confluent
producer.confluent.monitoring.interceptor.security.protocol=SASL_SSL
producer.confluent.monitoring.interceptor.ssl.keystore.password=confluent
producer.confluent.monitoring.interceptor.ssl.keystore.location=/etc/kafka/secrets/connect.keystore.jks
producer.confluent.monitoring.interceptor.ssl.truststore.location=/etc/kafka/secrets/connect.truststore.jks
producer.confluent.monitoring.interceptor.ssl.truststore.password=confluent
producer.confluent.monitoring.interceptor.ssl.key.password=confluent


consumer.security.protocol=SASL_SSL
consumer.ssl.keystore.password=confluent
consumer.ssl.keystore.location=/etc/kafka/secrets/connect.keystore.jks
consumer.ssl.truststore.location=/etc/kafka/secrets/connect.truststore.jks
consumer.ssl.truststore.password=confluent
consumer.ssl.key.password=confluent
consumer.confluent.monitoring.interceptor.security.protocol=SASL_SSL
consumer.confluent.monitoring.interceptor.ssl.keystore.password=confluent
consumer.confluent.monitoring.interceptor.ssl.keystore.location=/etc/kafka/secrets/connect.keystore.jks
consumer.confluent.monitoring.interceptor.ssl.truststore.location=/etc/kafka/secrets/connect.truststore.jks
consumer.confluent.monitoring.interceptor.ssl.truststore.password=confluent
consumer.confluent.monitoring.interceptor.ssl.key.password=confluent

sasl.mechanism=OAUTHBEARER
sasl.login.callback.handler.class=io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler
sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required username="connectAdmin" password="connectAdmin" metadataServerUrls="http://kafka1:18090,http://kafka2:28090";

connector.client.config.override.policy=All

producer.sasl.mechanism=OAUTHBEARER
producer.sasl.login.callback.handler.class=io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler
producer.confluent.monitoring.interceptor.sasl.mechanism=OAUTHBEARER
producer.confluent.monitoring.interceptor.sasl.login.callback.handler.class=io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler
producer.confluent.monitoring.interceptor.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required username="connectAdmin" password="connectAdmin" metadataServerUrls="http://kafka1:18090,http://kafka2:28090";

consumer.sasl.mechanism=OAUTHBEARER
consumer.sasl.login.callback.handler.class=io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler
consumer.confluent.monitoring.interceptor.sasl.mechanism=OAUTHBEARER
consumer.confluent.monitoring.interceptor.sasl.login.callback.handler.class=io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler
consumer.confluent.monitoring.interceptor.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required username="connectAdmin" password="connectAdmin" metadataServerUrls="http://kafka1:18090,http://kafka2:28090";

admin.security.protocol=SASL_SSL
admin.sasl.mechanism=OAUTHBEARER
admin.sasl.login.callback.handler.class=io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler
admin.ssl.keystore.password=confluent
admin.ssl.keystore.location=/etc/kafka/secrets/connect.keystore.jks
admin.ssl.truststore.location=/etc/kafka/secrets/connect.truststore.jks
admin.ssl.truststore.password=confluent
admin.ssl.key.password=confluent

# For replicator
rest.extension.classes=io.confluent.connect.replicator.monitoring.ReplicatorMonitoringExtension,io.confluent.connect.security.ConnectSecurityExtension,io.confluent.connect.secretregistry.ConnectSecretRegistryExtension
rest.servlet.initializor.classes=io.confluent.common.security.jetty.initializer.InstallBearerOrBasicSecurityHandler

confluent.metadata.bootstrap.server.urls=http://kafka1:18090,http://kafka2:28090
confluent.metadata.basic.auth.user.info=connectAdmin:connectAdmin
confluent.metadata.http.auth.credentials.provider=BASIC
public.key.path=/etc/kafka/secrets/mds/public.pem

config.providers=secret
config.providers.secret.class=io.confluent.connect.secretregistry.rbac.config.provider.InternalSecretConfigProvider
config.providers.secret.param.master.encryption.key=password1234
config.providers.secret.param.kafkastore.bootstrap.servers=kafka1:10091,kafka2:20091
config.providers.secret.param.kafkastore.security.protocol=SASL_SSL
config.providers.secret.param.kafkastore.ssl.keystore.password=confluent
config.providers.secret.param.kafkastore.ssl.keystore.location=/etc/kafka/secrets/connect.keystore.jks
config.providers.secret.param.kafkastore.ssl.truststore.location=/etc/kafka/secrets/connect.truststore.jks
config.providers.secret.param.kafkastore.ssl.truststore.password=confluent
config.providers.secret.param.kafkastore.ssl.key.password=confluent
config.providers.secret.param.kafkastore.ssl.endpoint.identification.algorithm=https
config.providers.secret.param.kafkastore.sasl.mechanism=OAUTHBEARER
config.providers.secret.param.kafkastore.sasl.login.callback.handler.class=io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler
config.providers.secret.param.kafkastore.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required username="connectAdmin" \
              password="connectAdmin" \
              metadataServerUrls="http://kafka1:18090,http://kafka2:28090";

ssl.cipher.suites=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256

plugin.path=/usr/share/java,/usr/share/confluent-hub-components

