---
version: '3.4'
services:
  prometheus:
    image: prom/prometheus:v2.29.2
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      example.com: {}

  grafana:
    image: grafana/grafana:8.1.3
    container_name: grafana
    hostname: grafana
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_USERS_ALLOW_SIGN_UP=false"
      - "GF_INSTALL_PLUGINS=grafana-piechart-panel"
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      example.com: {}

networks:
  example.com:
    name: "example.com"
    driver: bridge
