---
version: '3.4'
services:
  restproxy:
    environment:
      KAFKA_REST_SSL_CLIENT_AUTH: 'true'
      KAFKA_REST_CONFLUENT_REST_AUTH_SSL_PRINCIPAL_MAPPING_RULES: RULE:^CN=([^,]*),.*$$/$$1/,DEFAULT
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_KAFKA_REST_RESOURCE_EXTENSION_CLASS: io.confluent.kafkarest.security.KafkaRestSecurityResourceExtension
