---
version: '3.4'
services:
  restproxy:
    image: confluentinc/cp-kafka-rest:$TAG
    hostname: restproxy
    container_name: restproxy
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_CONFLUENT_REST_AUTH_PROPAGATE_METHOD: JETTY_AUTH
      KAFKA_REST_AUTHENTICATION_METHOD: BASIC
      KAFKA_REST_AUTHENTICATION_REALM: KafkaRest
      KAFKA_REST_AUTHENTICATION_ROLES: admin
      KAFKA_REST_KAFKA_REST_RESOURCE_EXTENSION_CLASS: io.confluent.kafkarest.security.KafkaRestSecurityResourceExtension
      KAFKAREST_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/restproxy.jaas
    volumes:
      - ./secrets:/etc/kafka/secrets
