---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
  image:
    application: confluentinc/cp-enterprise-control-center:$TAG
    init: confluentinc/confluent-init-container:$INIT_TAG
  dataVolumeCapacity: 10Gi
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
    ksqldb:
    - name: ksqldb
      url: http://ksqldb.confluent.svc.cluster.local:8088
    connect:
    - name: connect
      url: http://connect.confluent.svc.cluster.local:8083
#  authentication:
#    type: ldap
#    ldap:
#      roles: [Kafka,Developers]
#      restrictedRoles: [Developers]
#      property:
#        useLdaps : "false"
#        debug: "true"
#        contextFactory: "com.sun.jndi.ldap.LdapCtxFactory"
#        hostname: "openldap.confluent.svc.cluster.local"
#        port: "389"
#        bindDn: "cn=admin,dc=example,dc=com"
#        bindPassword: "admin"
#        authenticationMethod: "simple"
#        forceBindingLogin: "false"
#        userBaseDn: "ou=users,dc=example,dc=com"
#        userObjectClass: "inetOrgPerson"
#        userRdnAttribute: "uid"
#        userIdAttribute: "cn"
#        roleBaseDn: "ou=groups,dc=example,dc=com"
#        roleNameAttribute: "cn"
#        roleMemberAttribute: "memberUid"
#        roleObjectClass: "posixGroup"
#        userPasswordAttribute: "userPassword"
