---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent
spec:
  replicas: 3
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
  image:
    application: confluentinc/cp-zookeeper:$TAG
    init: confluentinc/confluent-init-container:$INIT_TAG
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
