plugin: amazon.aws.aws_ec2
regions:
- ap-southeast-2
filters:
  tag:Owner: avin
  instance-state-name: running
hostnames:
  - dns-name
  #- name: "private-ip-address"
  #  separator: ' || '
  #  prefix: "ip-address"
keyed_groups:
  - key: tags.Name
    separator: ""
  - key: tags.Owner
    separator: ""




