sasl.mechanism=OAUTHBEARER
security.protocol=SASL_SSL
#ssl.truststore.location=/Users/avin/confluentinc/confluent/security/rbac/scripts/security/client.truststore.jks
ssl.truststore.location=/etc/kafka/secrets/client.truststore.jks
ssl.truststore.password=confluent
sasl.login.callback.handler.class=io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler
sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
username="normalUser" \
password="normalUser" \
metadataServerUrls="http://kafka1:18090";
