ssl.truststore.location=/etc/kafka/secrets/ksqldb-server.truststore.jks
ssl.keystore.location=/etc/kafka/secrets/ksqldb-server.keystore.jks
#ssl.truststore.location=/Users/avin/confluentinc/confluent/security/rbac/scripts/security/ksqldb-server.truststore.jks
ssl.truststore.password=confluent
ssl.keystore.password=confluent
ssl.key.password=confluent


