---
version: '3.4'
services:
  kafka:
    cpus: 0.7
    environment:
      KAFKA_CONFLUENT_CLUSTER_LINK_ENABLE: "true"

  kafka1:
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:12181"
      KAFKA_CONFLUENT_CLUSTER_LINK_ENABLE: "true"

